### ISSUE TITLE
建议第一贴

### ISSUE THREAD

**Issue by chineselzh** [didikee/MDReader#1]
请问这个阅读器有没有计划支持`WebDAV `？
谢谢！

**Comment by didikee** [comment]
@chineselzh `WebDAV`是啥？维基解释：[基于万维网的分布式创作和版本控制（WebDAV）是一组基于超文本传输协议的技术集合，有利于用户间协同编辑和管理存储在万维网服务器文档](https://zh.wikipedia.org/wiki/WebDAV)

能详细科普下吗？

**Comment by chineselzh** [comment]
就是一种像FTP那种协议，具体我也不太清楚，嘿嘿，只是赶脚用起来很爽，特别是传送小文件之类的很舒服。。。
老大你在`坚果云`注册一个号试下嘛，再在酷安下一下`易码`，通过webdav建立连接，很方便的存储文件，具体我也说不清楚，老大试试就知道了。。。

**Comment by didikee** [comment]
@chineselzh 嗯，我看了下，目前不准备做那些，我只是想做一个简单的能打开导出html的，这个app只是我另外一个计划中的项目中的一个功能点。你的主意很好，我又涨见识了，哈哈，谢谢了！
